### ISSUE TITLE
Crash on kotlin1.3

### ISSUE THREAD

**Issue by RubyLichtenstein** [ShipBook/ShipBookSDK-Android#1]
Process: com.rubylichtenstein.outconnect, PID: 16971
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/ThreadPoolDispatcherKt;
        at io.shipbook.shipbooksdk.Networking.SessionManager.<clinit>(SessionManager.kt:31)
        at io.shipbook.shipbooksdk.ShipBook$Companion.start(ShipBook.kt:23)
        at io.shipbook.shipbooksdk.ShipBook$Companion.start$default(ShipBook.kt:22)
        at com.rubylichtenstein.outconnect.app.MyApplication.onCreate(MyApplication.kt:89)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.experimental.ThreadPoolDispatcherKt" on path: DexPathList[[zip file "/data/app/com.rubylichtenstein.outconnect-QfBg6-nmo-3Sr5ByPYqVUg==/base.apk"],nativeLibraryDirectories=[/data/app/com.rubylichtenstein.outconnect-QfBg6-nmo-3Sr5ByPYqVUg==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.shipbook.shipbooksdk.Networking.SessionManager.<clinit>(SessionManager.kt:31) 
        at io.shipbook.shipbooksdk.ShipBook$Companion.start(ShipBook.kt:23) 
        at io.shipbook.shipbooksdk.ShipBook$Companion.start$default(ShipBook.kt:22) 
        at com.rubylichtenstein.outconnect.app.MyApplication.onCreate(MyApplication.kt:89) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by elishas** [comment]
merged your branch
